#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := lora-test-app

# go up to main app and reference components dir from there
EXTRA_COMPONENT_DIRS = $(PROJECT_PATH)/../../../lib	

include $(IDF_PATH)/make/project.mk

